movies={  "Bollywood": [
    "Mother India",
    "Mughal-e-Azam",
    "Pyaasa",
    "Kaagaz Ke Phool",
    "Do Bigha Zamin",
    "Awaara",
    "Shree 420",
    "Guide",
    "Anand",
    "Aradhana",
    "Amar Prem",
    "Chupke Chupke",
    "Gol Maal",
    "Deewar",
    "Sholay",
    "Zanjeer",
    "Don",
    "Bobby",
    "Abhimaan",
    "Bawarchi",
    "Guddi",
    "Mili",
    "Namak Haraam",
    "Koshish",
    "Jewel Thief",
    "Teesri Manzil",
    "CID",
    "Sahib Bibi Aur Ghulam",
    "Bandini",
    "Madhumati",
    "Chalti Ka Naam Gaadi",
    "Junglee",
    "Garm Hava",
    "Upkar",
    "Purab Aur Paschim",
    "Yaadon Ki Baaraat",
    "Pakeezah",
    "Umrao Jaan",
    "Satyakam",
    "Naya Daur",
    "Anupama",
    "Bees Saal Baad",
    "Mere Mehboob",
    "Victoria No. 203",
    "Seeta Aur Geeta",
    "Karz",
    "Muqaddar Ka Sikandar",
    "Sujata",
    "Waqt",
    "Johny Mera Naam",
    "Mr. India",
    "Qayamat Se Qayamat Tak",
    "Maine Pyar Kiya",
    "Hum Aapke Hain Koun..!",
    "Dilwale Dulhania Le Jayenge",
    "Kuch Kuch Hota Hai",
    "Baazigar",
    "Darr",
    "Khalnayak",
    "Jo Jeeta Wohi Sikandar",
    "Andaz Apna Apna",
    "Rangeela",
    "Satya",
    "Border",
    "Roja",
    "Bombay",
    "Dil Se..",
    "Agneepath",
    "Tezaab",
    "Parinda",
    "Lamhe",
    "Chandni",
    "Betaab",
    "Arth",
    "Masoom",
    "Saaransh",
    "Ram Lakhan",
    "Tridev",
    "Ghayal",
    "Damini",
    "Karan Arjun",
    "Gupt",
    "Virasat",
    "Bandit Queen",
    "Tamanna",
    "Maachis",
    "Zakhm",
    "Hum Dil De Chuke Sanam",
    "Sarfarosh",
    "Vaastav",
    "Hera Pheri",
    "Mohabbatein",
    "Aashiqui",
    "Khamoshi: The Musical",
    "Kabhi Haan Kabhi Naa",
    "Angoor",
    "Shakti",
    "Coolie",
    "Sadma",
    "Lagaan",
    "Dil Chahta Hai",
    "Swades",
    "Rang De Basanti",
    "Taare Zameen Par",
    "3 Idiots",
    "Chak De! India",
    "Munna Bhai M.B.B.S.",
    "Lage Raho Munna Bhai",
    "Black",
    "Omkara",
    "Khosla Ka Ghosla",
    "A Wednesday!",
    "Johnny Gaddaar",
    "Company",
    "Gangaajal",
    "Sarkar",
    "Dev.D",
    "Oye Lucky! Lucky Oye!",
    "Life in a... Metro",
    "Rock On!!",
    "Wake Up Sid",
    "Fashion",
    "Guru",
    "Jab We Met",
    "Veer-Zaara",
    "Kal Ho Naa Ho",
    "Kabhi Khushi Kabhie Gham...",
    "Hum Tum",
    "Dhoom",
    "Dhoom 2",
    "Koi... Mil Gaya",
    "Krrish",
    "Don (2006)",
    "Bhool Bhulaiyaa",
    "Welcome",
    "Phir Hera Pheri",
    "Golmaal: Fun Unlimited",
    "Bunty Aur Babli",
    "Yuva",
    "Hazaaron Khwaishein Aisi",
    "Page 3",
    "Corporate",
    "Chandni Bar",
    "Dor",
    "Iqbal",
    "Kabul Express",
    "Firaaq",
    "Main Hoon Na",
    "Partner",
    "Singh Is Kinng",
    "New York",
    "Kaminey",
    "Love Aaj Kal",
    "Ghajini",
    "Wanted",
    "Namastey London",
    "Delhi-6",
    "Paa",
    "Udaan",
    "Rocket Singh: Salesman of the Year",
    "Karthik Calling Karthik",
    "Vivah",
    "Jodhaa Akbar",
    "Fanaa",
    "My Name Is Khan",
    "Dostana",
    "No Smoking",
    "Taxi No. 9211",
    "Being Cyrus",
    "Mumbai Meri Jaan",
    "Dil Dosti Etc",
    "Zindagi Na Milegi Dobara",
    "Rockstar",
    "Barfi!",
    "Kahaani",
    "Gangs of Wasseypur",
    "Gangs of Wasseypur 2",
    "English Vinglish",
    "Vicky Donor",
    "Queen",
    "Highway",
    "Haider",
    "PK",
    "Piku",
    "Bajrangi Bhaijaan",
    "Drishyam",
    "Talvar",
    "Masaan",
    "Tamasha",
    "Kapoor & Sons",
    "Dangal",
    "Dear Zindagi",
    "Pink",
    "Airlift",
    "Neerja",
    "Aligarh",
    "Udta Punjab",
    "Raman Raghav 2.0",
    "Andhadhun",
    "Tumbbad",
    "Stree",
    "Badhaai Ho",
    "Raazi",
    "October",
    "Mulk",
    "Pad Man",
    "Sanju",
    "Article 15",
    "Gully Boy",
    "Chhichhore",
    "Super 30",
    "War",
    "Bala",
    "Dream Girl",
    "URI: The Surgical Strike",
    "Thappad",
    "Ludo",
    "Bulbbul",
    "Shershaah",
    "Mimi",
    "Sardar Udham",
    "Sherni",
    "Chandigarh Kare Aashiqui",
    "Atrangi Re",
    "The Kashmir Files",
    "Gangubai Kathiawadi",
    "Bhool Bhulaiyaa 2",
    "Drishyam 2",
    "Bhediya",
    "Qala",
    "Monica, O My Darling",
    "Vikram Vedha",
    "An Action Hero",
    "Pathaan",
    "Jawan",
    "Animal",
    "Dunki",
    "12th Fail",
    "Rocky Aur Rani Kii Prem Kahaani",
    "OMG 2",
    "Sam Bahadur",
    "Laapataa Ladies",
    "Fighter",
    "Kill",
    "Stree 2",
    "Munjya",
    "Bhakshak",
    "Maidaan",
    "Chandu Champion",
    "Crew",
    "Merry Christmas",
    "Article 370",
    "Madgaon Express",
    "Sector 36",
    "Jigra",
    "Baby John",
    "Sky Force",
    "Chhaava",
    "Kesari Chapter 2",
    "120 Bahadur",
    "Badhaai Do",
    "Darlings",
    "Jersey",
    "Kaala Paani",
    "Kathal",
    "Bawaal",
    "Lust Stories",
    "Lust Stories 2",
    "Delhi Crime",
    "Sacred Games",
    "Paatal Lok",
    "Scam 1992",
    "The Family Man",
    "Asur",
    "Mirzapur",
    "Farzi",
    "Kohrra",
    "Jamtara",
    "Delhi Belly",
    "Lootera",
    "Ship of Theseus",
    "Special 26",
    "Kai Po Che!",
    "Madras Cafe",
    "NH10",
    "Dum Laga Ke Haisha",
    "Karwaan",
    "Sonchiriya",
    "Mard Ko Dard Nahi Hota",
    "Newton",
    "Lipstick Under My Burkha",
    "Badlapur",
    "Ek Villain",
    "Bhavesh Joshi Superhero"
  ],
"Hollywood": ["Casablanca",
    "Citizen Kane",
    "Gone with the Wind",
    "The Wizard of Oz",
    "It's a Wonderful Life",
    "Sunset Boulevard",
    "All About Eve",
    "Singin' in the Rain",
    "Rear Window",
    "Vertigo",
    "North by Northwest",
    "The African Queen",
    "Roman Holiday",
    "High Noon",
    "Some Like It Hot",
    "Ben-Hur",
    "Lawrence of Arabia",
    "To Kill a Mockingbird",
    "Doctor Zhivago",
    "The Sound of Music",
    "The Graduate",
    "Bonnie and Clyde",
    "Cool Hand Luke",
    "2001: A Space Odyssey",
    "The Producers",
    "The Last Picture Show",
    "A Clockwork Orange",
    "The Godfather",
    "The Godfather Part II",
    "Chinatown",
    "Jaws",
    "One Flew Over the Cuckoo's Nest",
    "Rocky",
    "Taxi Driver",
    "Network",
    "Apocalypse Now",
    "Star Wars",
    "Annie Hall",
    "The Exorcist",
    "The Sting",
    "The Bridge on the River Kwai",
    "West Side Story",
    "The Apartment",
    "Breakfast at Tiffany's",
    "Mary Poppins",
    "Butch Cassidy and the Sundance Kid",
    "The French Connection",
    "Patton",
    "The Ten Commandments",
    "From Here to Eternity",
    "Raiders of the Lost Ark",
    "E.T. the Extra-Terrestrial",
    "Blade Runner",
    "The Shining",
    "The Empire Strikes Back",
    "Return of the Jedi",
    "Back to the Future",
    "The Breakfast Club",
    "Top Gun",
    "Aliens",
    "Die Hard",
    "The Terminator",
    "Dead Poets Society",
    "Rain Man",
    "When Harry Met Sally...",
    "Batman",
    "Goodfellas",
    "Home Alone",
    "Dances with Wolves",
    "Pretty Woman",
    "The Silence of the Lambs",
    "Terminator 2: Judgment Day",
    "JFK",
    "Unforgiven",
    "The Fugitive",
    "Pulp Fiction",
    "Forrest Gump",
    "The Shawshank Redemption",
    "The Lion King",
    "Braveheart",
    "Toy Story",
    "Apollo 13",
    "Se7en",
    "The Usual Suspects",
    "Heat",
    "Independence Day",
    "The English Patient",
    "Titanic",
    "L.A. Confidential",
    "Good Will Hunting",
    "Saving Private Ryan",
    "The Truman Show",
    "The Big Lebowski",
    "American Beauty",
    "The Matrix",
    "The Sixth Sense",
    "Fight Club",
    "The Green Mile",
    "Office Space",
    "The Insider",
    "Gladiator",
    "Memento",
    "Crouching Tiger, Hidden Dragon",
    "Traffic",
    "Almost Famous",
    "X-Men",
    "A Beautiful Mind",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Harry Potter and the Sorcerer's Stone",
    "Monsters, Inc.",
    "Ocean's Eleven",
    "Spider-Man",
    "The Lord of the Rings: The Two Towers",
    "Minority Report",
    "The Bourne Identity",
    "Chicago",
    "The Lord of the Rings: The Return of the King",
    "Finding Nemo",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Kill Bill: Vol. 1",
    "Lost in Translation",
    "The Incredibles",
    "Eternal Sunshine of the Spotless Mind",
    "Million Dollar Baby",
    "Sideways",
    "Batman Begins",
    "Crash",
    "Brokeback Mountain",
    "The Departed",
    "Casino Royale",
    "Pan's Labyrinth",
    "No Country for Old Men",
    "There Will Be Blood",
    "Ratatouille",
    "Juno",
    "Zodiac",
    "Michael Clayton",
    "Atonement",
    "The Dark Knight",
    "WALL·E",
    "Slumdog Millionaire",
    "The Curious Case of Benjamin Button",
    "Avatar",
    "Up",
    "Inglourious Basterds",
    "Up in the Air",
    "District 9",
    "Star Trek",
    "The Hangover",
    "Sherlock Holmes",
    "Fantastic Mr. Fox",
    "Coraline",
    "The Blind Side",
    "Precious",
    "The Hurt Locker",
    "Warrior",
    "Hugo",
    "Toy Story 3",
    "Inception",
    "The Social Network",
    "Black Swan",
    "The King's Speech",
    "True Grit",
    "127 Hours",
    "The Fighter",
    "The Kids Are All Right",
    "The Town",
    "Inside Llewyn Davis",
    "Dallas Buyers Club",
    "The Wolf of Wall Street",
    "Gone Girl",
    "The Big Short",
    "Arrival",
    "Manchester by the Sea",
    "Hacksaw Ridge",
    "Baby Driver",
    "The Trial of the Chicago 7",
    "Minari",
    "The Menu",
    "The Artist",
    "The Avengers",
    "The Dark Knight Rises",
    "Skyfall",
    "Django Unchained",
    "Argo",
    "The Hobbit: An Unexpected Journey",
    "Silver Linings Playbook",
    "Life of Pi",
    "Zero Dark Thirty",
    "Les Misérables",
    "Gravity",
    "12 Years a Slave",
    "Her",
    "Captain America: The Winter Soldier",
    "Guardians of the Galaxy",
    "Birdman",
    "Whiplash",
    "Interstellar",
    "The Grand Budapest Hotel",
    "The Lego Movie",
    "Boyhood",
    "Mad Max: Fury Road",
    "Inside Out",
    "The Martian",
    "Spotlight",
    "Star Wars: The Force Awakens",
    "The Revenant",
    "Deadpool",
    "Zootopia",
    "Captain America: Civil War",
    "La La Land",
    "Moonlight",
    "Hidden Figures",
    "Get Out",
    "Logan",
    "Dunkirk",
    "Wonder Woman",
    "Blade Runner 2049",
    "The Shape of Water",
    "Three Billboards Outside Ebbing, Missouri",
    "Black Panther",
    "Avengers: Infinity War",
    "A Star Is Born",
    "Bohemian Rhapsody",
    "Spider-Man: Into the Spider-Verse",
    "Green Book",
    "Avengers: Endgame",
    "Joker",
    "Parasite",
    "1917",
    "The Irishman",
    "Once Upon a Time in Hollywood",
    "Knives Out",
    "Soul",
    "Tenet",
    "Promising Young Woman",
    "Nomadland",
    "Dune",
    "The Power of the Dog",
    "CODA",
    "Spider-Man: No Way Home",
    "The Batman",
    "Top Gun: Maverick",
    "Everything Everywhere All at Once",
    "Elvis",
    "The Whale",
    "Avatar: The Way of Water",
    "Oppenheimer",
    "Barbie",
    "Killers of the Flower Moon",
    "Poor Things",
    "Spider-Man: Across the Spider-Verse",
    "Guardians of the Galaxy Vol. 3",
    "Mission: Impossible – Dead Reckoning Part One",
    "John Wick: Chapter 4",
    "Napoleon",
    "The Holdovers",
    "Anatomy of a Fall",
    "Past Lives",
    "American Fiction",
    "Wonka",
    "Godzilla Minus One",
    "Dune: Part Two",
    "Inside Out 2",
    "A Quiet Place: Day One",
    "Deadpool & Wolverine",
    "Alien: Romulus",
    "The Wild Robot",
    "Challengers",
    "Twisters",
    "The Fall Guy",
    "Furiosa: A Mad Max Saga",
    "The Substance",
    "Nosferatu",
    "Wicked",
    "Gladiator II",
    "Conclave",
    "The Zone of Interest",
    "The Boy and the Heron",
    "Perfect Days",
    "Civil War",
    "Late Night with the Devil",
    "Longlegs",
    "Saturday Night",
    "Beetlejuice Beetlejuice",
    "Mufasa: The Lion King",
    "Flow",
    "Smile 2",
    "The Instigators",
    "Horizon: An American Saga – Chapter 1",
    "The Ministry of Ungentlemanly Warfare"],
  
  "Marvelwood": [
    "Iron Man",
    "The Incredible Hulk",
    "Iron Man 2",
    "Thor",
    "Captain America: The First Avenger",
    "The Avengers",
    "Iron Man 3",
    "Thor: The Dark World",
    "Captain America: The Winter Soldier",
    "Guardians of the Galaxy",
    "Avengers: Age of Ultron",
    "Ant-Man",
    "Captain America: Civil War",
    "Doctor Strange",
    "Guardians of the Galaxy Vol. 2",
    "Spider-Man: Homecoming",
    "Thor: Ragnarok",
    "Black Panther",
    "Avengers: Infinity War",
    "Ant-Man and the Wasp",
    "Captain Marvel",
    "Avengers: Endgame",
    "Spider-Man: Far From Home",
    "Black Widow",
    "Shang-Chi and the Legend of the Ten Rings",
    "Eternals",
    "Spider-Man: No Way Home",
    "Doctor Strange in the Multiverse of Madness",
    "Thor: Love and Thunder",
    "Black Panther: Wakanda Forever",
    "Ant-Man and the Wasp: Quantumania",
    "Guardians of the Galaxy Vol. 3",
    "The Marvels",
    "Deadpool & Wolverine",
    "Captain America: Brave New World",
    "Thunderbolts*",
    "The Fantastic Four: First Steps",
    "Blade",
    "Avengers: Doomsday",
    "Spider-Man: Brand New Day",
    "Avengers: Secret Wars",
    "Howard the Duck",
    "Fantastic Four",
    "The Fantastic Four: Rise of the Silver Surfer",
    "Spider-Man",
    "Spider-Man 2",
    "Spider-Man 3",
    "The Amazing Spider-Man",
    "The Amazing Spider-Man 2",
    "Daredevil",
    "Elektra",
    "Hulk",
    "The Punisher",
    "Punisher: War Zone",
    "Ghost Rider",
    "Ghost Rider: Spirit of Vengeance",
    "X-Men",
    "X2: X-Men United",
    "X-Men: The Last Stand",
    "X-Men Origins: Wolverine",
    "X-Men: First Class",
    "The Wolverine",
    "X-Men: Days of Future Past",
    "X-Men: Apocalypse",
    "Dark Phoenix",
    "The New Mutants",
    "Deadpool",
    "Deadpool 2",
    "Venom",
    "Venom: Let There Be Carnage",
    "Venom: The Last Dance",
    "Morbius",
    "Madame Web",
    "Kraven the Hunter",
    "Spider-Man: Into the Spider-Verse",
    "Spider-Man: Across the Spider-Verse",
    "Spider-Man: Beyond the Spider-Verse",
    "Blade II",
    "Blade: Trinity",
    "Man-Thing",
    "Fantastic Four (1994)",
    "Fantastic Four (2015)",
    "Ultimate Avengers: The Movie",
    "Ultimate Avengers 2: Rise of the Panther",
    "The Invincible Iron Man",
    "Doctor Strange: The Sorcerer Supreme",
    "Next Avengers: Heroes of Tomorrow",
    "Hulk Vs",
    "Planet Hulk",
    "Thor: Tales of Asgard",
    "Iron Man: Rise of Technovore",
    "Iron Man & Hulk: Heroes United",
    "Avengers Confidential: Black Widow & Punisher",
    "Iron Man & Captain America: Heroes United",
    "Marvel Super Hero Adventures: Frost Fight!",
    "Hulk: Where Monsters Dwell",
    "Marvel Rising: Secret Warriors",
    "Marvel Rising: Chasing Ghosts",
    "Marvel Rising: Heart of Iron",
    "Marvel Rising: Battle of the Bands",
    "Marvel Rising: Operation Shuri",
    "Marvel Rising: Playing with Fire"
  ]
}